### ISSUE TITLE
Distributed package error

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#550]
I removed the `ogusa-dev` conda environment today and reinstalled it using the `conda env create` command from my `OG-USA` top directory. I then ran `run_examples/run_ogusa_example.py` and got the following error:

```
Traceback (most recent call last):
  File "run_examples/run_ogusa_example.py", line 7, in <module>
    from distributed import Client
ImportError: No module named distributed
```

When I type `conda list` in my environment, I get the following list, which includes the `distributed` package.

```
Traceback (most recent call last):
  File "run_ogusa_example.py", line 7, in <module>
    from distributed import Client
ImportError: No module named distributed
(ogusa-dev) richardevans@Richards-MBP run_examples % conda list
# packages in environment at /Users/richardevans/opt/anaconda3/envs/ogusa-dev:
#
# Name                    Version                   Build  Channel
apipkg                    1.5                        py_0    conda-forge
astroid                   2.3.3                    py37_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
brotlipy                  0.7.0           py37h0b31af3_1000    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cachetools                4.1.0                    pypi_0    pypi
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
coverage                  5.1              py37h9bfed18_0    conda-forge
cryptography              2.8              py37he655712_2    conda-forge
cs-kit                    1.11.0                   pypi_0    pypi
cs-storage                1.9.0                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h0b31af3_0    conda-forge
dask                      2.14.0                     py_0    conda-forge
dask-core                 2.14.0                     py_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
distributed               2.14.0           py37hc8dfbb8_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
execnet                   1.7.1                      py_0    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
fsspec                    0.7.2                      py_0    conda-forge
gcsfs                     0.6.1                    pypi_0    pypi
google-auth               1.14.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
heapdict                  1.0.1                      py_0    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
isort                     4.3.21           py37hc8dfbb8_1    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
kiwisolver                1.2.0            py37ha1cc60f_0    conda-forge
lazy-object-proxy         1.4.3            py37h9bfed18_2    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcxx                    10.0.0                        0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
llvmlite                  0.31.0           py37hb548287_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                h4a8c4bd_0    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
marshmallow               3.5.0                      py_0    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py37hddda452_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mkl                       2020.0                      166    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
msgpack-python            1.0.0            py37ha1cc60f_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numba                     0.48.0           py37h4f17bb1_0    conda-forge
numpy                     1.18.1           py37h7687784_1    conda-forge
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openpyxl                  3.0.3                      py_0    conda-forge
openssl                   1.1.1f               h0b31af3_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py37h94625e5_1    conda-forge
paramtools                0.13.1             pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pillow                    7.1.1            py37hfd78ece_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
psutil                    5.7.0            py37h9bfed18_1    conda-forge
py                        1.8.1                      py_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pylint                    2.4.4                    py37_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
pytest-cache              1.0                        py_2    conda-forge
pytest-forked             1.1.2                      py_0    conda-forge
pytest-pep8               1.0.6                      py_2    conda-forge
pytest-xdist              1.31.0                     py_0    conda-forge
python                    3.7.6           h90870a6_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3.1            py37h9bfed18_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scipy                     1.4.1            py37hce1b9e5_3    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
taxcalc                   2.9.0                    py37_0    PSLmodels
tblib                     1.6.0                      py_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
typed-ast                 1.4.1            py37h0b31af3_0    conda-forge
typing_extensions         3.7.4.1          py37hc8dfbb8_3    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py37h9bfed18_1    conda-forge
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.5                h0b31af3_0    conda-forge
yaml                      0.2.3                h0b31af3_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge
(ogusa-dev) richardevans@Richards-MBP run_examples % python run_ogusa_example.py
```
And my operating system is Mac OSX Catalina, and @benrpage1 had the same error on his Windows machine.

cc: @jdebacker

**Comment by jdebacker** [comment]
@hdoupe This is looking like an issue related to `dask` and `distributed` in python 3.7.  Have you run into any related issues?

I've not run into the issue and I have the same package versions of `dask` and `distributed` (2.14.0), but I noticed that I have python 3.6 in my environment whereas others with issues had 3.7.

**Comment by rickecon** [comment]
Disregard this error @jdebacker and @hdoupe. This was caused by not following the exact instructions for building the conda environment. It is solved by following the instructions in the OG-USA `README.md`.
